import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";
import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc, getDoc } from "firebase/firestore";

dotenv.config();

// Initialize Firebase using the configuration file generated by the platform if available
let db: any = null;
let firebaseEnabled = false;

// Fallback in-memory and local file store for shared itineraries in case Firebase is absent
const memorySharedStore = new Map<string, any>();
const LOCAL_SHARE_FILE = path.join(process.cwd(), "shared_itineraries_fallback.json");

function saveFallbackShare(id: string, itinerary: any) {
  memorySharedStore.set(id, itinerary);
  try {
    let currentStore: Record<string, any> = {};
    if (fs.existsSync(LOCAL_SHARE_FILE)) {
      currentStore = JSON.parse(fs.readFileSync(LOCAL_SHARE_FILE, "utf-8"));
    }
    currentStore[id] = itinerary;
    fs.writeFileSync(LOCAL_SHARE_FILE, JSON.stringify(currentStore, null, 2), "utf-8");
  } catch (err) {
    console.warn("[Fallback Share] Failed to persist fallback travel share file:", err);
  }
}

function getFallbackShare(id: string): any | null {
  if (memorySharedStore.has(id)) {
    return memorySharedStore.get(id);
  }
  try {
    if (fs.existsSync(LOCAL_SHARE_FILE)) {
      const currentStore = JSON.parse(fs.readFileSync(LOCAL_SHARE_FILE, "utf-8"));
      if (currentStore[id]) {
        memorySharedStore.set(id, currentStore[id]);
        return currentStore[id];
      }
    }
  } catch (err) {
    console.warn("[Fallback Share] Failed to read fallback travel share file:", err);
  }
  return null;
}

try {
  const configPath = path.join(process.cwd(), "firebase-applet-config.json");
  if (fs.existsSync(configPath)) {
    const firebaseConfig = JSON.parse(fs.readFileSync(configPath, "utf-8"));
    const firebaseApp = initializeApp(firebaseConfig);
    db = getFirestore(firebaseApp, firebaseConfig.firestoreDatabaseId);
    firebaseEnabled = true;
    console.log("[Firebase] Successfully initialized persistently using config file.");
  } else {
    console.warn("[Firebase] Config file missing. Sharing will fall back to local JSON storage.");
  }
} catch (error) {
  console.error("[Firebase] Initialization failed:", error);
}

// Mandated operation types and error format config for robust debugging
enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: any[];
  };
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: null,
      email: null,
      emailVerified: null,
      isAnonymous: null,
      tenantId: null,
      providerInfo: []
    },
    operationType,
    path
  };
  console.error('[Firebase Database Audit] Failure Detected: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Initialize Gemini SDK with telemetry header requested in the skill
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

/**
 * Helper to call Gemini API with robust retry and automatic model fallback.
 * Checks for transient errors (like 503 high demand or 429 rate limit)
 * and retries with exponential backoff.
 * If gemini-3.5-flash remains unavailable, it automatically falls back to gemini-3.1-flash-lite.
 */
async function generateContentWithRetryAndFallback(params: {
  contents: any;
  config: any;
  systemInstruction?: string;
}) {
  const primaryModel = "gemini-3.5-flash";
  const backupModel = "gemini-3.1-flash-lite";
  
  const callWithBackoff = async (modelName: string, maxRetries = 3, initialDelayMs = 1000) => {
    let attempt = 0;
    while (true) {
      try {
        console.log(`[Gemini API] Querying model ${modelName} (Attempt ${attempt + 1}/${maxRetries})...`);
        const response = await ai.models.generateContent({
          model: modelName,
          contents: params.contents,
          config: {
            ...params.config,
            ...(params.systemInstruction ? { systemInstruction: params.systemInstruction } : {}),
          }
        });
        return response;
      } catch (err: any) {
        attempt++;
        const errMsg = err.message || String(err);
        const errStatus = err.status || (err.error && err.error.code) || 0;
        
        // Check for common transient codes: 503 (Unavailable), 429 (Rate limit / Resource Exhausted), 500 (Internal Server Error)
        const isTransient = 
          errMsg.includes("503") || 
          errMsg.includes("status: 503") ||
          errMsg.includes("UNAVAILABLE") || 
          errMsg.includes("429") || 
          errMsg.includes("RESOURCE_EXHAUSTED") ||
          errMsg.includes("500") ||
          errStatus === 503 ||
          errStatus === 429 ||
          errStatus === 500;
          
        if (isTransient && attempt < maxRetries) {
          const delay = initialDelayMs * Math.pow(2, attempt - 1);
          console.warn(`[Gemini API Retry] Model ${modelName} failed with transient error: "${errMsg}". Retrying in ${delay}ms...`);
          await new Promise(resolve => setTimeout(resolve, delay));
          continue;
        }
        throw err;
      }
    }
  };

  try {
    // Attempt with the primary model first (max 2 attempts to minimize latency pressure)
    const response = await callWithBackoff(primaryModel, 2, 800);
    return { response, modelUsed: primaryModel };
  } catch (primaryError: any) {
    console.error(`[Gemini API Primary Error] Primary model "${primaryModel}" completely unsuccessful:`, primaryError.message || primaryError);
    
    // Check if it's transient/unavailable/demand-related so we fallback to the lighter backup model
    console.log(`[Gemini API Fallback] Triggering automatic backup fallback to model: "${backupModel}"...`);
    try {
      const response = await callWithBackoff(backupModel, 2, 800);
      return { response, modelUsed: backupModel };
    } catch (backupError: any) {
      console.error(`[Gemini API Backup Error] Fallback model "${backupModel}" also unsuccessful:`, backupError.message || backupError);
      throw primaryError; // Throw the primary error to show the root cause of the demand issue
    }
  }
}

async function startServer() {
  const app = express();
  app.use(express.json());

  const PORT = 3000;

// Top Curated Seasonal Recommendations for May 2026 (Late Spring / Early Summer)
const CURATED_RECOMMENDATIONS = [
  {
    name: "Amalfi Coast",
    country: "Italy",
    tagline: "Clifftop villages, warm turquoise waters, and lemon orchards",
    whyNow: "Late Spring offers gorgeous 72-78°F (22-25°C) beach-perfect days before peak crowds arrive in July/August.",
    description: "Experience the ultimate coastal escape. Explore pastel-colored houses stacked high on cliffs, sail the Tyrrhenian Sea, and enjoy fresh seafood and limoncello.",
    themeTags: ["beaches", "food", "history", "boating", "culture"],
    recommendedDurationDays: 5,
    estimatedBudgets: {
      budget: 150,
      balanced: 320,
      luxury: 750
    },
    highlights: ["Positano panoramic hike", "Private boat ride around Capri", "Ravello cliffside gardens"]
  },
  {
    name: "Kyoto",
    country: "Japan",
    tagline: "Serene bamboo groves, Zen gardens, and historic tea houses",
    whyNow: "May brings warm, sunny days with lush, vibrant green maple leaves (Shinryoku), perfect for outdoor exploration with low humidity.",
    description: "Japan's cultural capital boasts thousands of classical Buddhist temples, gardens, imperial palaces, Shinto shrines, and traditional wooden houses.",
    themeTags: ["history", "culture", "gardens", "food", "photography"],
    recommendedDurationDays: 4,
    estimatedBudgets: {
      budget: 85,
      balanced: 190,
      luxury: 520
    },
    highlights: ["Fushimi Inari gates at sunset", "Arashiyama bamboo path", "Gion traditional tea ceremony"]
  },
  {
    name: "Banff & Jasper National Parks",
    country: "Canada",
    tagline: "Turquoise alpine lakes and massive snow-capped Rocky Mountains",
    whyNow: "Late May is the magical transition where glacier-fed lakes like Lake Louise and Moraine Lake start to thaw, revealing stunning turquoise hues.",
    description: "Canada's premier mountain escape is perfect for hikers and wildlife watchers. Savor alpine hot springs, drive scenic icefield highways, and see bears emerging.",
    themeTags: ["hiking", "adventure", "wildlife", "roadtrip", "mountains"],
    recommendedDurationDays: 6,
    estimatedBudgets: {
      budget: 110,
      balanced: 230,
      luxury: 600
    },
    highlights: ["Icefields Parkway roadtrip scenic views", "Moraine Lake rental canoe", "Banff Upper Hot Springs soak"]
  },
  {
    name: "Maui, Hawaii",
    country: "USA",
    tagline: "Golden beaches, lava trails, and the legendary Road to Hana",
    whyNow: "May sits in an exquisite sweet spot post-Spring Break and pre-Summer vacation, boasting calm winds, 80°F waters, and great resort rates.",
    description: "A tropical paradise featuring dramatic coastlines, cascading waterfalls, volcanic stargazing on Haleakala, and snorkeling with green sea turtles.",
    themeTags: ["beaches", "hiking", "roadtrip", "relaxed", "snorkeling"],
    recommendedDurationDays: 5,
    estimatedBudgets: {
      budget: 180,
      balanced: 350,
      luxury: 850
    },
    highlights: ["Snorkeling in Molokini Crater", "Drive the magical Road to Hana", "Sunset stargazing on Haleakala Summit"]
  },
  {
    name: "New York City",
    country: "USA",
    tagline: "Skyscrapers, world-class theatre, and endless energy",
    whyNow: "Late Spring weather is highly pleasant (approx 70°F) for walking around Central Park, walking the High Line, and outdoor rooftop dining.",
    description: "The capital of culture, fashion, and cuisine. Witness iconic yellow taxis, famous museums (Met, MoMA), and Broadway shows.",
    themeTags: ["culture", "food", "shopping", "museums", "city_walks"],
    recommendedDurationDays: 4,
    estimatedBudgets: {
      budget: 130,
      balanced: 280,
      luxury: 680
    },
    highlights: ["Broadway broadway musical booking", "Picnic in fully-bloomed Central Park", "High Line and Chelsea Market sunset stroll"]
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    tagline: "The adventure capital of the Southern Hemisphere",
    whyNow: "May offers a stunning golden autumn foliage palette transitioning into winter. Perfect for crisp hikes, cozy vineyard tours, and early snow activities.",
    description: "Nestled on the shores of Lake Wakatipu and surrounded by the dramatic Remarkables mountain range, it is-the ultimate adrenaline and scenery hub.",
    themeTags: ["adventure", "distilleries", "wine", "hiking", "nature"],
    recommendedDurationDays: 6,
    estimatedBudgets: {
      budget: 95,
      balanced: 210,
      luxury: 550
    },
    highlights: ["Shotover River jet boat", "Gibbston Valley wine & craft beer tasting", "Scenic gondola and luge ride"]
  }
];

// 1. Recommendations Endpoint
app.get("/api/itinerary/test-ai", async (req, res) => {
  try {
    const keyExists = !!process.env.GEMINI_API_KEY;
    const keySnippet = process.env.GEMINI_API_KEY ? `${process.env.GEMINI_API_KEY.slice(0, 6)}...${process.env.GEMINI_API_KEY.slice(-4)}` : "None";
    
    console.log(`[Diagnostic] API key exists: ${keyExists} (${keySnippet})`);
    
    if (!process.env.GEMINI_API_KEY) {
      return res.json({ 
        success: false, 
        error: "GEMINI_API_KEY environment variable is missing completely on the server. Please add GEMINI_API_KEY in the Settings > Secrets panel.",
        keyExists,
        keySnippet
      });
    }

    const testResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: "Respond in 3 words: Yes it works",
    });

    return res.json({ 
      success: true, 
      text: testResponse.text,
      keyExists,
      keySnippet
    });
  } catch (err: any) {
    console.error("[Diagnostic] Gemini diagnostic error:", err);
    return res.json({ 
      success: false, 
      error: err.message || String(err),
      stack: err.stack,
      keyExists: !!process.env.GEMINI_API_KEY
    });
  }
});

app.get("/api/itinerary/recommendations", (req, res) => {
  res.json(CURATED_RECOMMENDATIONS);
});

// --- Shared Itineraries Storage ---
// We have migrated from stateless local file-based storage to a persistent Firestore database
// to prevent link expirations and publish stalling issues when Cloud Run containers scale or restart.

async function saveSharedItineraryFirebase(id: string, itinerary: any): Promise<void> {
  const docPath = `shared_itineraries/${id}`;
  if (!db) {
    saveFallbackShare(id, itinerary);
    return;
  }
  try {
    const docRef = doc(db, 'shared_itineraries', id);
    // Ensure the payload structure is clean and append creation metadata
    const payload = {
      ...itinerary,
      createdAt: new Date().toISOString()
    };
    await setDoc(docRef, payload);
  } catch (err) {
    console.warn('[Firebase Database] Failed to write. Using local fallback...', err);
    saveFallbackShare(id, itinerary);
  }
}

async function getSharedItineraryFirebase(id: string): Promise<any | null> {
  const docPath = `shared_itineraries/${id}`;
  if (!db) {
    return getFallbackShare(id);
  }
  try {
    const docRef = doc(db, 'shared_itineraries', id);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return docSnap.data();
    }
    return getFallbackShare(id);
  } catch (err) {
    console.warn('[Firebase Database] Failed to read. Checking local fallback...', err);
    return getFallbackShare(id);
  }
}

// 2. Share Save Endpoint
app.post("/api/itinerary/share", async (req, res) => {
  try {
    const { itinerary } = req.body;
    if (!itinerary) {
      return res.status(400).json({ error: "Missing itinerary to share" });
    }
    // Generate a unique 9-character trip sharing identification code
    const id = Math.random().toString(36).substring(2, 11);
    await saveSharedItineraryFirebase(id, itinerary);
    return res.json({ success: true, id });
  } catch (err: any) {
    console.error("Share endpoint error:", err);
    return res.status(500).json({ error: err.message || "Failed to save sharing instance" });
  }
});

// 3. Share Retrieval Endpoint
app.get("/api/itinerary/share/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const itinerary = await getSharedItineraryFirebase(id);
    if (!itinerary) {
      return res.status(404).json({ error: "Itinerary not found or link has expired." });
    }
    return res.json({ success: true, itinerary });
  } catch (err: any) {
    console.error("Share Retrieval endpoint error:", err);
    return res.status(500).json({ error: err.message || "Failed to load sharing instance" });
  }
});



// Helper to determine typical dynamic sliding budget ranges for a selected location
app.get("/api/itinerary/calculate-local-budget", async (req, res) => {
  const { destination } = req.query;
  const destName = String(destination || "").trim();

  // Pick suitable benchmarks based on typical standard city profiles
  const lowerDest = destName.toLowerCase();
  let baseCost = { budget: 100, balanced: 220, luxury: 600 };

  if (lowerDest.includes("tokyo") || lowerDest.includes("japan") || lowerDest.includes("kyoto")) {
    baseCost = { budget: 90, balanced: 200, luxury: 550 };
  } else if (lowerDest.includes("amalfi") || lowerDest.includes("italy") || lowerDest.includes("rome") || lowerDest.includes("paris") || lowerDest.includes("london") || lowerDest.includes("swiss") || lowerDest.includes("switzerland")) {
    baseCost = { budget: 140, balanced: 300, luxury: 700 };
  } else if (lowerDest.includes("hawaii") || lowerDest.includes("maui") || lowerDest.includes("new york") || lowerDest.includes("nyc") || lowerDest.includes("california") || lowerDest.includes("san francisco")) {
    baseCost = { budget: 160, balanced: 320, luxury: 800 };
  } else if (lowerDest.includes("thailand") || lowerDest.includes("bali") || lowerDest.includes("indonesia") || lowerDest.includes("vietnam") || lowerDest.includes("india") || lowerDest.includes("costa rica")) {
    baseCost = { budget: 40, balanced: 90, luxury: 290 };
  } else if (lowerDest.includes("canada") || lowerDest.includes("banff") || lowerDest.includes("alaska")) {
    baseCost = { budget: 110, balanced: 240, luxury: 650 };
  } else if (lowerDest.includes("new zealand") || lowerDest.includes("queenstown") || lowerDest.includes("australia") || lowerDest.includes("sydney")) {
    baseCost = { budget: 100, balanced: 220, luxury: 580 };
  } else {
    // If not in standard pre-calculated, query Gemini dynamically if API key is present
    if (destName && process.env.GEMINI_API_KEY) {
      try {
        const { response } = await generateContentWithRetryAndFallback({
          contents: `Provide a realistic, modern travel daily cost estimate (in USD, per standard individual, excluding flights) for the destination: "${destName}".
We need three tiers:
- "budget": low cost (hostels, street food, super inexpensive)
- "balanced": standard comfort (mid-range hotels, sit-down dining, typical entrance tickets)
- "luxury": high-end luxury (4-5 star hotels, fine dining, private tours)

Respond STRICTLY with a single JSON object containing only these three fields: "budget" (integer), "balanced" (integer), "luxury" (integer).
Example format:
{ "budget": 65, "balanced": 160, "luxury": 420 }
Do not include any styling, explanation, or markdown blocks. Return only valid raw JSON.`,
          config: {}
        });

        const textResponse = response.text?.trim() || "";
        const jsonStr = textResponse.replace(/```json|```/gi, "").trim();
        const parsed = JSON.parse(jsonStr);
        if (parsed && typeof parsed.budget === 'number' && typeof parsed.balanced === 'number' && typeof parsed.luxury === 'number') {
          baseCost = {
            budget: Math.max(15, parsed.budget),
            balanced: Math.max(parsed.budget + 10, parsed.balanced),
            luxury: Math.max(parsed.balanced + 25, parsed.luxury)
          };
          console.log(`[Budget] Dynamic calculation for "${destName}" succeeded:`, baseCost);
          return res.json(baseCost);
        }
      } catch (err: any) {
        console.warn(`[Budget] Dynamic budget generation call failed for "${destName}":`, err.message || err);
      }
    }
  }

  res.json(baseCost);
});

// Define structural response schema globally to prevent duplicate declarations and enable schema safety in prompt modifications
const itineraryResponseSchema = {
  type: Type.OBJECT,
  properties: {
    destination: { type: Type.STRING, description: "Normalized destination name" },
    durationDays: { type: Type.INTEGER, description: "Final confirmed trip duration in days" },
    citizenshipStatus: { type: Type.STRING, description: "Citizenship entered with" },
    visaConditions: { type: Type.STRING, description: "Detailed summary of entry/visa conditions for this specific user" },
    recommendedTravelDates: { type: Type.STRING, description: "Best recommended dates or time period to go" },
    whyThisRecommendation: { type: Type.STRING, description: "A highly descriptive, comprehensive breakdown of why this customized transport structure, timing/dates, and local neighborhoods were recommended. Give deep local context, vibe details, and specific local advice." },
    whyThisRecommendationLinks: {
      type: Type.ARRAY,
      description: "Supporting references, seasonal articles, or search queries explaining why this was recommended.",
      items: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING, description: "Display name for the link, e.g. 'Kyoto Cherry Blossom Forecast' or 'Paris Metro Practical Guide'" },
          url: { type: Type.STRING, description: "A highly relevant URL or specific Google Search string formatted with '+' instead of spaces. E.g. 'https://www.google.com/search?q=best+months+to+visit+paris+seasonal+guide'" }
        },
        required: ["title", "url"]
        }
    },
    days: {
      type: Type.ARRAY,
      description: "List of scheduled days in order",
      items: {
        type: Type.OBJECT,
        properties: {
          dayNumber: { type: Type.INTEGER },
          date: { type: Type.STRING, description: "The specific formatted calendar date for this day of travel (e.g., 'Wednesday, May 27, 2026' or 'Thursday, May 28, 2026' based on the travel timeframe). Spelled out with weekday, month, day, year." },
          theme: { type: Type.STRING, description: "Daily overview focus e.g. Historical Explorer" },
          activities: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING, description: "A unique string ID for editing/deleting tasks. Generate UUID format or unique tag like act-1-1" },
                time: { type: Type.STRING, description: "Time of the day e.g. 09:00 AM - 10:30 AM" },
                activityName: { type: Type.STRING, description: "Highly specific name of the activity, detailing the real-world venue, specific restaurant name, or sightseeing attraction rather than generic words. Never use placeholders." },
                description: { type: Type.STRING, description: "A deeply detailed paragraph of 3-4 sentences packed with real, highly practical concierge-level recommendations. Name specific dishes to order (with local specialty name), exact panoramic viewpoint coordinates or paths, little-known historical secrets, or exact local advice to beat the crowd." },
                locationName: { type: Type.STRING, description: "Exact name of the real restaurant, museum, park, etc. Must be a specific, real physical location." },
                estimatedCost: { type: Type.NUMBER, description: "Estimated cost in USD for this participant" },
                bookingNeeded: { type: Type.BOOLEAN, description: "Whether this must be booked in advance" },
                bookingDeepLink: { type: Type.STRING, description: "Search/Booking deep URL link directly related to book this spot" },
                travelTimeToNextMs: { type: Type.INTEGER, description: "Travel transfer duration to next activity in minutes" },
                travelDetailsToNext: { type: Type.STRING, description: "Short description of travel to the next activity e.g. Walk 10 min, or drive 15 min via Hwy 1" }
              },
              required: ["id", "time", "activityName", "description", "locationName", "estimatedCost", "bookingNeeded", "bookingDeepLink"]
            }
          }
        },
        required: ["dayNumber", "date", "theme", "activities"]
      }
    },
    preTravelChecks: {
      type: Type.ARRAY,
      description: "A pre-travel preparation tasks checklist",
      items: {
        type: Type.OBJECT,
        properties: {
          id: { type: Type.STRING, description: "Checklist item unique string id" },
          task: { type: Type.STRING, description: "The task required e.g. Secure National Parks Pass" },
          category: { type: Type.STRING, description: "One of: booking, documents, packing, visa, other" },
          dueDate: { type: Type.STRING, description: "Due date or relative timeline e.g. 2 weeks before departure" },
          notes: { type: Type.STRING },
          completed: { type: Type.BOOLEAN, description: "Always false initially" }
        },
        required: ["id", "task", "category", "dueDate", "notes", "completed"]
      }
    },
    budget: {
      type: Type.OBJECT,
      description: "Approximate budgeting details tailored for the traveler's preference and counts",
      properties: {
        accommodation: {
          type: Type.OBJECT,
          properties: {
            type: { type: Type.STRING, description: "Accommodation standard description e.g. Mid-range Boutique Hotel" },
            estimatedCost: { type: Type.NUMBER, description: "Estimated standard cost in USD" },
            explanation: { type: Type.STRING },
            deepLink: { type: Type.STRING, description: "Clickable Hotel/Airbnb search url" }
          },
          required: ["type", "estimatedCost", "explanation", "deepLink"]
        },
        transport: {
          type: Type.OBJECT,
          properties: {
            type: { type: Type.STRING, description: "E.g. Rental SUV / Local Trains" },
            estimatedCost: { type: Type.NUMBER, description: "Estimated dynamic transport cost in USD" },
            explanation: { type: Type.STRING, description: "A very short, punchy 1-sentence description or strategy." },
            deepLink: { type: Type.STRING, description: "Clickable flight/car rentals search url" }
          },
          required: ["type", "estimatedCost", "explanation", "deepLink"]
        },
        activities: {
          type: Type.OBJECT,
          properties: {
            estimatedCost: { type: Type.NUMBER, description: "Activities cost aggregation in USD" },
            explanation: { type: Type.STRING, description: "A very concise, scannable, punchy summary of key bookings, tickets, and admissions included (strictly keep under 1-2 short sentences)." }
          },
          required: ["estimatedCost", "explanation"]
        },
        foodAndMisc: {
          type: Type.OBJECT,
          properties: {
            estimatedCost: { type: Type.NUMBER, description: "Daily meals and incidentals aggregation" },
            explanation: { type: Type.STRING, description: "Concise description detailing dining guideline or rate (strictly keep to 1 short sentence)." }
          },
          required: ["estimatedCost", "explanation"]
        },
        totalEstimated: { type: Type.NUMBER, description: "Sum of all cost elements in USD" },
        currency: { type: Type.STRING, description: "Usually 'USD'" }
      },
      required: ["accommodation", "transport", "activities", "foodAndMisc", "totalEstimated", "currency"]
    },
    flightDetails: {
      type: Type.OBJECT,
      description: "Recommended flight options, stops information, dynamic deal alerts, and pricing advisories based on selected departure and destination",
      properties: {
        preferredStops: { type: Type.STRING, description: "Value reflecting user stops preferences: 'nonstop' or 'one' or 'any'" },
        recommendedFlights: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              airline: { type: Type.STRING, description: "Official airline name e.g. Delta Air Lines" },
              flightNumber: { type: Type.STRING, description: "Logical flight code e.g. DL-184" },
              departureAirport: { type: Type.STRING },
              arrivalAirport: { type: Type.STRING },
              departureTime: { type: Type.STRING },
              arrivalTime: { type: Type.STRING },
              duration: { type: Type.STRING, description: "E.g. 5h 30m or 14h 20m" },
              stops: { type: Type.INTEGER, description: "Numeric stops: 0 for nonstop, 1, 2" },
              stopsDetail: { type: Type.STRING, description: "Layover detail label, e.g. 'Nonstop' or 'Layover in ORD'" },
              priceUSD: { type: Type.NUMBER, description: "Approximate standard ticket price in USD" },
              cabinClass: { type: Type.STRING, description: "Economy / Business / First class" }
            },
            required: ["airline", "flightNumber", "departureAirport", "arrivalAirport", "departureTime", "arrivalTime", "duration", "stops", "priceUSD", "cabinClass"]
          }
        },
        dealAlert: { type: Type.STRING, description: "Dynamic advice on deals or day shifts for better price: e.g. 'Save $120 if you fly on Wednesday instead of Saturday!'" },
        bestPriceAdvice: { type: Type.STRING, description: "A detailed 2-3 sentence overview advising user how/when to book for the cheapest rates to this location." },
        bookingDeepLink: { type: Type.STRING, description: "Google Flights booking query link customized with departures and destination airport codes or city names" }
      },
      required: ["preferredStops", "recommendedFlights", "bestPriceAdvice", "bookingDeepLink"]
    },
    accommodationRecommendation: {
      type: Type.OBJECT,
      description: "Custom Accommodation stay style and base camp location strategy",
      properties: {
        stayType: { type: Type.STRING, description: "Style of stay: 'hotel' or 'airbnb' or 'split' or 'other'" },
        heading: { type: Type.STRING, description: "A dynamic engaging headline summary" },
        locationStrategy: { type: Type.STRING, description: "Nights split breakdown or base camp geography recommendation" },
        detailedReasoning: { type: Type.STRING, description: "Detailed reasons contrasting Hotels/Airbnbs, analyzing layout of the island/city, transit benefits" }
      },
      required: ["stayType", "heading", "locationStrategy", "detailedReasoning"]
    }
  },
  required: [
    "destination",
    "durationDays",
    "citizenshipStatus",
    "visaConditions",
    "recommendedTravelDates",
    "whyThisRecommendation",
    "whyThisRecommendationLinks",
    "days",
    "preTravelChecks",
    "budget",
    "flightDetails",
    "accommodationRecommendation"
  ]
};

// A highly realistic helper to map airport codes and flights based on preferences
function getFallbackFlights(departure: string, destination: string, preferredStops: string = 'any') {
  const departText = (departure || "").toLowerCase();
  const destText = (destination || "").toLowerCase();

  let depCode = "JFK";
  if (departText.includes("los angeles") || departText.includes("lax")) depCode = "LAX";
  else if (departText.includes("san francisco") || departText.includes("sfo")) depCode = "SFO";
  else if (departText.includes("chicago") || departText.includes("ord")) depCode = "ORD";
  else if (departText.includes("london") || departText.includes("lhr")) depCode = "LHR";
  else if (departText.includes("tokyo") || departText.includes("nrt") || departText.includes("hnd")) depCode = "NRT";
  else if (departText.includes("miami") || departText.includes("mia")) depCode = "MIA";
  else if (departText.includes("boston") || departText.includes("bos")) depCode = "BOS";
  else if (departText.includes("seattle") || departText.includes("sea")) depCode = "SEA";
  else if (departText.includes("toronto") || departText.includes("yyz")) depCode = "YYZ";
  else if (departure && departure.replace(/[^a-zA-Z]/g, '').length >= 3) {
    depCode = departure.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase();
  }

  let arrCode = "NAP"; 
  let region = "Europe";
  if (destText.includes("amalfi") || destText.includes("napoli") || destText.includes("naples")) {
    arrCode = "NAP";
    region = "Europe";
  } else if (destText.includes("rome") || destText.includes("roma") || destText.includes("italy")) {
    arrCode = "FCO";
    region = "Europe";
  } else if (destText.includes("kyoto") || destText.includes("osaka") || destText.includes("kix")) {
    arrCode = "KIX";
    region = "Asia";
  } else if (destText.includes("tokyo") || destText.includes("japan")) {
    arrCode = "NRT";
    region = "Asia";
  } else if (destText.includes("banff") || destText.includes("calgary") || destText.includes("yyc")) {
    arrCode = "YYC";
    region = "Americas";
  } else if (destText.includes("jasper") || destText.includes("edmonton")) {
    arrCode = "YEG";
    region = "Americas";
  } else if (destText.includes("maui") || destText.includes("kahului") || destText.includes("ogg")) {
    arrCode = "OGG";
    region = "Pacific";
  } else if (destText.includes("big island") || destText.includes("kona") || destText.includes("koa")) {
    arrCode = "KOA";
    region = "Pacific";
  } else if (destText.includes("hilo") || destText.includes("ito")) {
    arrCode = "ITO";
    region = "Pacific";
  } else if (destText.includes("new york") || destText.includes("nyc") || destText.includes("jfk")) {
    arrCode = "JFK";
    region = "Americas";
  } else if (destText.includes("queenstown") || destText.includes("zqn")) {
    arrCode = "ZQN";
    region = "Pacific";
  } else if (destination && destination.replace(/[^a-zA-Z]/g, '').length >= 3) {
    arrCode = destination.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase();
  }

  const allFlightsPool = [
    {
      airline: "Delta Air Lines",
      flightNumber: "DL-402",
      departureAirport: depCode,
      arrivalAirport: arrCode,
      departureTime: "08:30 AM",
      arrivalTime: "09:45 PM",
      duration: "7h 15m",
      stops: 0,
      stopsDetail: "Nonstop",
      priceUSD: region === 'Americas' ? 340 : region === 'Europe' ? 760 : region === 'Asia' ? 1120 : 1250,
      cabinClass: "Economy"
    },
    {
      airline: "United Airlines",
      flightNumber: "UA-904",
      departureAirport: depCode,
      arrivalAirport: arrCode,
      departureTime: "11:15 AM",
      arrivalTime: "11:55 PM",
      duration: "7h 40m",
      stops: 0,
      stopsDetail: "Nonstop",
      priceUSD: region === 'Americas' ? 380 : region === 'Europe' ? 820 : region === 'Asia' ? 1180 : 1300,
      cabinClass: "Economy"
    },
    {
      airline: "Lufthansa",
      flightNumber: "LH-431",
      departureAirport: depCode,
      arrivalAirport: arrCode,
      departureTime: "04:15 PM",
      arrivalTime: "10:30 AM (+1 Day)",
      duration: "11h 15m",
      stops: 1,
      stopsDetail: "Layover in FRA (1h 45m)",
      priceUSD: region === 'Americas' ? 420 : region === 'Europe' ? 680 : region === 'Asia' ? 980 : 1100,
      cabinClass: "Economy"
    },
    {
      airline: "Air France",
      flightNumber: "AF-015",
      departureAirport: depCode,
      arrivalAirport: arrCode,
      departureTime: "05:30 PM",
      arrivalTime: "10:15 AM (+1 Day)",
      duration: "10h 45m",
      stops: 1,
      stopsDetail: "Layover in CDG (1h 50m)",
      priceUSD: region === 'Americas' ? 410 : region === 'Europe' ? 610 : region === 'Asia' ? 920 : 1020,
      cabinClass: "Economy"
    }
  ];

  let filtered = allFlightsPool;
  if (preferredStops === 'nonstop') {
    filtered = allFlightsPool.filter(f => f.stops === 0);
  } else if (preferredStops === 'one') {
    filtered = allFlightsPool.filter(f => f.stops === 1);
  }

  if (filtered.length === 0) {
    filtered = allFlightsPool.slice(0, 2);
  }

  let dealAlert = "Lowest Price Alert: Tuesday departures represent average savings of $115. Shift departure dates from weekend to midweek for optimal airfare rates.";
  if (region === 'Europe') {
    dealAlert = "European Flight Deals: Midweek departures on Tuesdays or Wednesdays represent dynamic airfare savings of $185 per seat.";
  } else if (region === 'Asia') {
    dealAlert = "International Route Alert: Tuesday/Wednesday departures avoid peak weekend multipliers. Shifting days can yield up to $220 in savings.";
  } else if (region === 'Pacific') {
    dealAlert = "Pacific Route Deal Finder: Flights to islands show lower pricing profiles on Wednesday departures. Avoid peak Friday long-weekends.";
  }

  const bestPriceAdvice = `Historical aviation indexes show the optimal booking lead time for flights on the ${depCode} to ${arrCode} corridor is 45 to 65 days out. Setting search tracker notifications on Google Flights ensures pricing optimization.`;

  return {
    preferredStops,
    recommendedFlights: [],
    dealAlert,
    bestPriceAdvice,
    bookingDeepLink: `https://www.google.com/search?q=google+flights+from+${depCode}+to+${arrCode}`
  };
}

// A highly realistic, curated fallback itinerary generator to guarantee graceful degradation
// and prevent loading/spinning states from hanging if the Gemini API is blocked or slow
function generateFallbackItinerary(preferences: any) {
  const {
    citizenship,
    departure,
    destination,
    isInternational,
    isRoadtrip,
    roadtripType,
    hasDates,
    startDate,
    endDate,
    durationDays = 5,
    accommodationType = "both",
    transportType = "ai_recommended",
    pace = "balanced",
    peopleCount = 1,
    selectedInterests = [],
    customTags = [],
    avoidTags = [],
    budgetType = "balanced",
    customDailyBudgetLimit = 220,
    preferredStops = "any"
  } = preferences;

  const destClean = (destination || "").split(',')[0].trim() || "Destination";
  const departClean = (departure || "").split(',')[0].trim() || "Departure";
  const datesLabel = hasDates && startDate && endDate ? `${startDate} to ${endDate}` : "Late Spring/Summer 2026 Season Selection";

  const resolvedAccommodationType = accommodationType === "ai_recommended" ? "both" : accommodationType;
  const resolvedTransportType = transportType === "ai_recommended" ? "rental" : transportType;

  const totalDaily = customDailyBudgetLimit || 220;
  const totalTripCost = totalDaily * durationDays * peopleCount;
  
  const accommodationCost = Math.round(totalTripCost * 0.45);
  const transportCost = Math.round(totalTripCost * 0.18);
  const foodCost = Math.round(totalTripCost * 0.22);
  const activitiesTotalLimit = Math.round(totalTripCost * 0.15);

  let hotelDeepLink = `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(destination || "")}`;
  if (hasDates && startDate && endDate) {
    hotelDeepLink = `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(destination || "")}&checkin=${startDate}&checkout=${endDate}`;
  }
  let flightsDeepLink = `https://www.google.com/search?q=flights+from+${encodeURIComponent(departure || "")}+to+${encodeURIComponent(destination || "")}`;
  if (hasDates && startDate && endDate) {
    flightsDeepLink = `https://www.google.com/search?q=google+flights+from+${encodeURIComponent(departure || "")}+to+${encodeURIComponent(destination || "")}+departing+${startDate}+returning+${endDate}`;
  }
  let transitDeepLink = `https://www.google.com/search?q=car+rental+in+${encodeURIComponent(destination || "")}`;
  if (hasDates && startDate && endDate) {
    transitDeepLink = `https://www.google.com/search?q=car+rental+in+${encodeURIComponent(destination || "")}+from+${startDate}+to+${endDate}`;
  }

  const accommodationTitle = accommodationType === 'hotel' 
    ? `Curated 4-Star Boutique Hotel in ${destClean}` 
    : accommodationType === 'airbnb' 
    ? `Charming Local Premium Villa/Airbnb in ${destClean}` 
    : accommodationType === 'ai_recommended'
    ? `Wander AI Recommended Lodgings (Comfortable hybrid of boutique hotels & stylish local homes) near ${destClean}`
    : `Comfortable Guest Suites & Boutique Stays near ${destClean}`;

  const transportTitle = transportType === 'rental' 
    ? "Private Full-Size SUV Rental" 
    : transportType === 'taxi_public' 
    ? "Local Subway Passes, Express Trains, & Rideshares" 
    : `Convenient Managed Shuttle & ${isRoadtrip ? "Roadtrip Vehicle" : "Subway Passes"}`;

  // Spots Database
  const amalfiSpots = {
    coffee: ["Espresso & Sfogliatella at La Zagara Cafe", "Pastries & morning tea at Pasticceria Pansa in Amalfi Piazza", "Fresh pastries at Sal De Riso", "Sunrise cappuccino at Caffè Positano"],
    morning: ["Sunrise stroll along Positano's cliff paths to Spiaggia Grande", "Private chartered boat excursion around Capri Island", "Scenic hiking of the Path of the Gods (Sentiero degli Dei)", "Explore the historical center and Cathedral of Amalfi Town"],
    lunch: ["Handmade Lemon Pasta with prawns at Ristorante Marina Grande", "Fresh Margherita Pizza at Donna Stella in a lemon garden", "Caprese Salad & seafood at Da Adolfo beachfront cove", "Gourmet seafood pasta at Trattoria da Gemma"],
    afternoon: ["Explore clifftop gardens and the Infinite Terrace of Villa Rufolo in Ravello", "Discover the clifftop gardens of Villa Cimbrone", "Guided exploration of the Emerald Grotto (Grotta dello Smeraldo)", "Stroll through the narrow lanes of Atrani fishing village"],
    sunset: ["Sunset drinks overlooking the cliffs at Praiano's One Fire Beach", "Limoncello spritz tasting at Franco's Bar in Positano", "Scenic sunset overlook from Ravello's Piazza Duomo", "Sunset coastal drive along the scenic SS163 highway"],
    dinner: ["Candlelit dinner under orange trees at Bistro Max in Positano", "Seafood with spectacular water views at Chez Black on Positano beach", "Traditional Michelin-level dining at Da Ciccio Cielo Mare Terra", "Elegant dining at Ristorante Al Mare with fresh daily catch"]
  };

  const kyotoSpots = {
    coffee: ["Matcha latte & custard buns at Arabica % Coffee Arashiyama", "Traditional matcha whisking session at Cafe Kombu", "Siphon coffee and sweet toasts at Smart Coffee Kyoto", "Morning tea at Blue Bottle Coffee Kyoto Nanzenji"],
    morning: ["Sunrise hike through 10,000 red torii gates of Fushimi Inari-taisha", "Quiet morning walk in Arashiyama Bamboo Grove", "Explore Kinkaku-ji's shimmering Golden Pavilion and lake", "Guided spiritual tour of historical Kiyomizu-dera Temple"],
    lunch: ["Traditional handmade Soba noodles at 500-year-old Honke Owariya", "Premium Gyu-Katsu (deep-fried beef cutlets) in central Gion", "Savory savory Okonomiyaki pancakes at Karafuneya Coffee", "Exquisite tofu multi-course hotpot at Tosuiro along the river"],
    afternoon: ["Zen rock garden meditation at Ryoan-ji Temple", "Traditional ceremonial tea brewing lesson in a Gion wooden Machiya", "Stroll and local street-food snack tasting at Nishiki Food Market", "Explore the historic wooden corridors of Nijo Castle (Nijo-jo)"],
    sunset: ["Sunset panorama of Kyoto from Kiyomizu-dera stage deck", "Evening walk through Yasaka Pagoda pathways in Higashiyama", "Stroll along the Kamogawa River banks watching the water flow", "Panoramic sunset view from Kyoto Tower observation deck"],
    dinner: ["Traditional multi-course Kaiseki cuisine at Gion Karyo", "Aged Wagyu beef teppanyaki at Otsuka in Kyoto center", "Casual Michelin-starred broth ramen at central Kyoto Shofudo", "Cozy Kyoto-style home-cooked Obanzai dishes at Menami"]
  };

  const banffSpots = {
    coffee: ["Espresso and fresh breakfast croissants at Whitebark Cafe", "Morning espresso and hot breakfast bowls at Wild Flour Bakery", "Hot chocolates and sweet rolls at Evelyn's Coffee Bar", "Morning drip coffee at Bear Street Tavern"],
    morning: ["Canoe ride on the turquoise waters of Moraine Lake", "Icefields Parkway spectacular glacier-fed roadtrip drive", "Scenic hike through Johnston Canyon trail's waterfalls", "Glacier Lake Louise hiking along the lakeshore path"],
    lunch: ["Wood-fired elk burgers and mountain fare at The Bison Restaurant", "Hearty mountain sandwiches and craft brews at Bear Street Tavern", "Swiss alpine cheese fondue at Waldhaus Restaurant", "Fresh local salmon salad at Tooloulous Cozy Diner"],
    afternoon: ["Relaxing bath in the warm pools of Banff Upper Hot Springs", "Stroll around the scenic loop paths of Lake Minnewanka", "Take the Sulphur Mountain Gondola to the panoramic boardwalk", "Explore historical cave formations at Cave and Basin Historic Site"],
    sunset: ["Golden hour photography overlooking Vermilion Lakes", "Sunset panoramic drive on Mount Norquay Scenic Overlook", "Lakeside sunset stroll around the shores of Pyramid Lake", "Scenic sunset views from Surprise Corner overlooking Banff Castle"],
    dinner: ["Gourmet alpine steak dining at The Maple Leaf Grille", "Cozy craft microbrewery pairing at Banff Ave Brewing Co", "Seared Alberta beef and fondue bowls at Grizzly House", "Fine Pacific Northwest dining at Chuck's Steakhouse"]
  };

  const genericSpots = {
    coffee: ["Charming cup of local espresso and baked rolls at a neighborhood bakery", "Artisanal barista drip coffee and fresh waffles at a scenic local spot", "Locally roasted custom-blend coffee and morning bites", "Cozy local cafe breakfast and freshly squeezed citrus juices"],
    morning: [`Panoramic guided city walk of ${destClean}'s historical landmarks`, `Morning tour of the most iconic heritage sites in ${destClean}`, `Sunrise photo session at the most famous viewpoint of ${destClean}`, `Explore local historic plazas and beautiful architectural corners`],
    lunch: ["Savor a high-quality traditional local lunch at a recommended tavern", "Delectable casual street food bites or gourmet local bistro lunch", "Fresh farm-to-table lunch specialty honoring seasonal ingredients", "Delightful regional specialties at an authentic family-run diner"],
    afternoon: [`Scenic canal or river cruise showcasing the heart of ${destClean}`, `Guided walking exploration of local botanical gardens and art museums`, `Exclusive craft workshops or local boutique shopping tours`, `Immersive exploration of local neighborhoods and artisanal studios`],
    sunset: [`Elegant sunset stroll along the primary waterfront of ${destClean}`, `Sip a sunset local signature drink overlooking clifftop vistas`, `Watch the golden hour sky light up from a high-altitude observation deck`, `Peaceful twilight stroll while the historic streetlights flicker on`],
    dinner: ["Decadent dinner featuring a custom chef-led gourmet tasting menu", "Candlelit dining with magnificent views at a top-rated cozy restaurant", "Authentic popular dining find loved by locals for regional recipes", "Celebrate a fantastic evening with live musical performances and fine wine"]
  };

  const lowerDest = destClean.toLowerCase();
  const spotSource = lowerDest.includes("amalfi") || lowerDest.includes("italy") ? amalfiSpots :
                     lowerDest.includes("kyoto") || lowerDest.includes("japan") ? kyotoSpots :
                     lowerDest.includes("banff") || lowerDest.includes("canada") || lowerDest.includes("jasper") ? banffSpots :
                     genericSpots;

  const days: any[] = [];
  
  for (let d = 1; d <= durationDays; d++) {
    const idx = (d - 1);
    
    let calculatedDate = "";
    if (hasDates && startDate) {
      try {
        const startParts = startDate.split('-');
        const start = new Date(Number(startParts[0]), Number(startParts[1]) - 1, Number(startParts[2]));
        const currentDay = new Date(start.getTime() + (d - 1) * 24 * 60 * 60 * 1000);
        const options: any = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        calculatedDate = currentDay.toLocaleDateString('en-US', options);
      } catch {
        calculatedDate = `Day ${d} (${startDate})`;
      }
    } else {
      try {
        const start = new Date(2026, 5, 15); // June 15, 2026
        const currentDay = new Date(start.getTime() + (d - 1) * 24 * 60 * 60 * 1000);
        const options: any = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        calculatedDate = currentDay.toLocaleDateString('en-US', options);
      } catch {
        calculatedDate = `Day ${d} (June 15, 2026)`;
      }
    }
    
    // Activity Candidate Slot Definitions (Hyper-Detailed & Personalized)
    const slot1Name = spotSource.coffee[idx % spotSource.coffee.length];
    const slot1Desc = `Kick off Day ${d} in the most relaxing local fashion. Take a moment to savor freshly brewed coffees, flaky specialty pastries, and map out your day elements.`;
    const slot1Loc = `Cozy Local Bakery, ${destClean}`;
    const slot1Cost = Math.round((totalDaily * 0.05));
    const slot1Link = `https://www.google.com/search?q=${encodeURIComponent(slot1Name + " in " + destClean)}`;
    
    const slot2Name = spotSource.morning[idx % spotSource.morning.length];
    const slot2Desc = `An enriching exploration of ${destClean}'s highlight structures. Walk through historic cobblestone squares, listen to the whisper of history, and snap high-contrast sunrise photographs.`;
    const slot2Loc = `${destClean} Cultural District`;
    const slot2Cost = Math.round((totalDaily * 0.15));
    const slot2Link = `https://www.google.com/search?q=book+tickets+for+${encodeURIComponent(slot2Name + " in " + destClean)}`;
    
    const slot3Name = spotSource.lunch[idx % spotSource.lunch.length];
    const slot3Desc = `Indulge in an exquisite, highly recommended local lunch specialty prepared with natural, farm-fresh local seasonal ingredients.`;
    const slot3Loc = `Handcrafted Food Tavern, ${destClean}`;
    const slot3Cost = Math.round((totalDaily * 0.10));
    const slot3Link = `https://www.google.com/search?q=reserve+table+at+${encodeURIComponent(slot3Name + " in " + destClean)}`;
    
    const slot4Name = spotSource.afternoon[idx % spotSource.afternoon.length];
    const slot4Desc = `Engage in a scenic afternoon trek or art museum walk customized to fit your active interest criteria. Gain deep panoramic views and explore hidden courtyard gardens.`;
    const slot4Loc = `${destClean} Discovery Trails`;
    const slot4Cost = Math.round((totalDaily * 0.13));
    const slot4Link = `https://www.google.com/search?q=book+tickets+for+${encodeURIComponent(slot4Name + " in " + destClean)}`;
    
    const slot5Name = spotSource.sunset[idx % spotSource.sunset.length];
    const slot5Desc = `An elegant twilight observation stroll along the scenic bay overlook points. Pause to watch the sky reflect in golden shades while drinking refreshing iced teas.`;
    const slot5Loc = `Sunset Panorama Deck, ${destClean}`;
    const slot5Cost = Math.round((totalDaily * 0.07));
    const slot5Link = `https://www.google.com/search?q=${encodeURIComponent(slot5Name + " in " + destClean)}`;
    
    const slot6Name = spotSource.dinner[idx % spotSource.dinner.length];
    const slot6Desc = `End of a breathtaking daily chapter. Sit down for candlelit fine dining at a highly rated culinary establishment featuring premium local recipes.`;
    const slot6Loc = `Fine Culinary Room, ${destClean}`;
    const slot6Cost = Math.round((totalDaily * 0.20));
    const slot6Link = `https://www.google.com/search?q=reserve+table+at+${encodeURIComponent(slot6Name + " in " + destClean)}`;

    const rawActivities: any[] = [];
    
    if (d === 1) {
      // ARRIVAL DAY LOGISTICS
      rawActivities.push({
        time: "10:30 AM - 12:00 PM",
        activityName: `Depart from standard terminals & flight from ${departClean}`,
        description: `Embark on your journey of a lifetime. Gather boarding passes, secure transit documents, and settle into flight cabin seating bound for ${destClean}.`,
        locationName: `${departClean} International Departure Gate`,
        estimatedCost: 0,
        bookingNeeded: true,
        bookingDeepLink: flightsDeepLink,
        travelTimeToNextMs: 120,
        travelDetailsToNext: "Transfer to ground taxi shuttle after arrival"
      });
      rawActivities.push({
        time: "02:30 PM - 03:30 PM",
        activityName: `Secure airport transfer & private hotel shuttle`,
        description: `Arrive in majestic ${destClean}. Greet your dedicated transfer shuttle or unlock your high-capacity ${transportType === 'rental' ? "SUV rental vehicle" : "taxi shuttle"} at standard rentals.`,
        locationName: `${destClean} Arrival Terminals`,
        estimatedCost: 0,
        bookingNeeded: false,
        bookingDeepLink: transitDeepLink,
        travelTimeToNextMs: 45,
        travelDetailsToNext: "Drive directly to local check-in counters"
      });
      rawActivities.push({
        time: "04:00 PM - 05:00 PM",
        activityName: `Official Accommodation Check-In & Refresh`,
        description: `Arrive at: ${accommodationTitle}. Complete administrative check-in requirements. Receive room key credentials, unpack bags safely, and refresh with spectacular scenic views.`,
        locationName: accommodationTitle,
        estimatedCost: 0,
        bookingNeeded: true,
        bookingDeepLink: hotelDeepLink,
        travelTimeToNextMs: 60,
        travelDetailsToNext: "Casual walk out to nearby local spots"
      });
      rawActivities.push({
        time: "07:30 PM - 09:30 PM",
        activityName: slot6Name,
        description: `Welcome Dinner! ` + slot6Desc,
        locationName: slot6Loc,
        estimatedCost: slot6Cost,
        bookingNeeded: true,
        bookingDeepLink: slot6Link,
        travelTimeToNextMs: 0,
        travelDetailsToNext: "Return directly to your cozy local accommodations"
      });
    } else if (d === durationDays) {
      // DEPARTURE DAY LOGISTICS
      rawActivities.push({
        time: "08:30 AM - 09:30 AM",
        activityName: slot1Name,
        description: `Last breakfast morning! ` + slot1Desc,
        locationName: slot1Loc,
        estimatedCost: slot1Cost,
        bookingNeeded: false,
        bookingDeepLink: slot1Link,
        travelTimeToNextMs: 45,
        travelDetailsToNext: "Head back to accommodation to consolidate packings"
      });
      rawActivities.push({
        time: "10:00 AM - 11:00 AM",
        activityName: `Accommodation Check-Out & Travel Prep`,
        description: `Finalize packing schedules. Settle incidentals with receptionist desk and complete official checkout procedures safely (standard checkout is at 11:00 AM).`,
        locationName: accommodationTitle,
        estimatedCost: 0,
        bookingNeeded: false,
        bookingDeepLink: hotelDeepLink,
        travelTimeToNextMs: 45,
        travelDetailsToNext: "Transfer to major flight halls"
      });
      rawActivities.push({
        time: "12:00 PM - 02:30 PM",
        activityName: `Flight Departure Back to ${departClean}`,
        description: `Proceed through airport scanners and board outbound flight back home. Savor beautiful photos and wonderful lasting experiences from this expedition.`,
        locationName: `${destClean} Departure Gate`,
        estimatedCost: 0,
        bookingNeeded: true,
        bookingDeepLink: flightsDeepLink,
        travelTimeToNextMs: 0,
        travelDetailsToNext: "Safe travels back!"
      });
    } else {
      // EXPLORATION DAYS FILTERED BY PACING PREFERENCE
      if (pace === 'relaxed') {
        // Relaxed gets 2 beautiful main items to maximize breathing room
        rawActivities.push({
          time: "09:30 AM - 12:30 PM",
          activityName: slot2Name,
          description: slot2Desc,
          locationName: slot2Loc,
          estimatedCost: slot2Cost,
          bookingNeeded: true,
          bookingDeepLink: slot2Link,
          travelTimeToNextMs: 90,
          travelDetailsToNext: "Enjoy a peaceful leisurely walk to your dining spot"
        });
        rawActivities.push({
          time: "05:00 PM - 08:00 PM",
          activityName: slot6Name,
          description: slot6Desc,
          locationName: slot6Loc,
          estimatedCost: slot6Cost,
          bookingNeeded: true,
          bookingDeepLink: slot6Link,
          travelTimeToNextMs: 0,
          travelDetailsToNext: "Ferry or taxi ride back to suites with spectacular views"
        });
      } else if (pace === 'balanced') {
        // Balanced layout gets EXACTLY 4 highly granular, structured blocks
        rawActivities.push({
          time: "08:30 AM - 10:00 AM",
          activityName: slot1Name,
          description: slot1Desc,
          locationName: slot1Loc,
          estimatedCost: slot1Cost,
          bookingNeeded: false,
          bookingDeepLink: slot1Link,
          travelTimeToNextMs: 30,
          travelDetailsToNext: "Transfer via local sidewalk paths"
        });
        rawActivities.push({
          time: "10:30 AM - 01:00 PM",
          activityName: slot2Name,
          description: slot2Desc,
          locationName: slot2Loc,
          estimatedCost: slot2Cost,
          bookingNeeded: true,
          bookingDeepLink: slot2Link,
          travelTimeToNextMs: 45,
          travelDetailsToNext: "Casual transfer to premium lunch reservation"
        });
        rawActivities.push({
          time: "02:00 PM - 05:00 PM",
          activityName: slot4Name,
          description: slot4Desc,
          locationName: slot4Loc,
          estimatedCost: slot4Cost,
          bookingNeeded: true,
          bookingDeepLink: slot4Link,
          travelTimeToNextMs: 60,
          travelDetailsToNext: "Refresh at suite before setting out to evening dinner"
        });
        rawActivities.push({
          time: "06:30 PM - 09:30 PM",
          activityName: slot6Name,
          description: slot6Desc,
          locationName: slot6Loc,
          estimatedCost: slot6Cost,
          bookingNeeded: true,
          bookingDeepLink: slot6Link,
          travelTimeToNextMs: 0,
          travelDetailsToNext: "Return directly to your cozy local accommodations"
        });
      } else {
        // Advanturous gets 5-6 fully dynamic action-packed slots
        rawActivities.push({
          time: "08:00 AM - 09:15 AM",
          activityName: slot1Name,
          description: slot1Desc,
          locationName: slot1Loc,
          estimatedCost: slot1Cost,
          bookingNeeded: false,
          bookingDeepLink: slot1Link,
          travelTimeToNextMs: 20,
          travelDetailsToNext: "Short local drive or active walking paths"
        });
        rawActivities.push({
          time: "10:00 AM - 12:30 PM",
          activityName: slot2Name,
          description: slot2Desc,
          locationName: slot2Loc,
          estimatedCost: slot2Cost,
          bookingNeeded: true,
          bookingDeepLink: slot2Link,
          travelTimeToNextMs: 35,
          travelDetailsToNext: "Gather gears and proceed to lunch tavern"
        });
        rawActivities.push({
          time: "01:00 PM - 02:30 PM",
          activityName: slot3Name,
          description: slot3Desc,
          locationName: slot3Loc,
          estimatedCost: slot3Cost,
          bookingNeeded: false,
          bookingDeepLink: slot3Link,
          travelTimeToNextMs: 30,
          travelDetailsToNext: "Active transit to afternoon sightseeing highlight"
        });
        rawActivities.push({
          time: "03:00 PM - 05:30 PM",
          activityName: slot4Name,
          description: slot4Desc,
          locationName: slot4Loc,
          estimatedCost: slot4Cost,
          bookingNeeded: true,
          bookingDeepLink: slot4Link,
          travelTimeToNextMs: 30,
          travelDetailsToNext: "Catch the sunset trolley or hike to lookout base"
        });
        rawActivities.push({
          time: "06:00 PM - 07:15 PM",
          activityName: slot5Name,
          description: slot5Desc,
          locationName: slot5Loc,
          estimatedCost: slot5Cost,
          bookingNeeded: false,
          bookingDeepLink: slot5Link,
          travelTimeToNextMs: 45,
          travelDetailsToNext: "Head back to shower and prepare for fine dining dress codes"
        });
        rawActivities.push({
          time: "08:00 PM - 10:30 PM",
          activityName: slot6Name,
          description: slot6Desc,
          locationName: slot6Loc,
          estimatedCost: slot6Cost,
          bookingNeeded: true,
          bookingDeepLink: slot6Link,
          travelTimeToNextMs: 0,
          travelDetailsToNext: "Return directly to your cozy local accommodations"
        });
      }
    }

    const activities = rawActivities.map((act, aIdx) => ({
      id: `fallback-act-${d}-${aIdx + 1}`,
      time: act.time,
      activityName: act.activityName,
      description: act.description,
      locationName: act.locationName,
      estimatedCost: act.estimatedCost,
      bookingNeeded: act.bookingNeeded,
      bookingDeepLink: act.bookingDeepLink,
      travelTimeToNextMs: act.travelTimeToNextMs || 0,
      travelDetailsToNext: act.travelDetailsToNext || "Prepare for the next highlight"
    }));

     days.push({
      dayNumber: d,
      date: calculatedDate,
      theme: d === 1 ? "Arrival, Settle Inn & Welcome" : d === durationDays ? "Farewells & Homebound Flights" : `Immersive Culture & ${selectedInterests[d % selectedInterests.length] || 'Premium Sightseeing'}`,
      activities: activities
    });
  }

  const preTravelChecks = [
    {
      id: "chk-1",
      task: `Initiate entry & passport check for a ${citizenship} citizen`,
      category: "visa",
      dueDate: "3 weeks before departure",
      notes: isInternational ? "Passport must keep at least 6 months validation; double-check local e-Visa forms." : "Domestic - keep standard state ID or driver's license handy.",
      completed: false
    },
    {
      id: "chk-2",
      task: `Finalize booking reservation at: ${accommodationTitle}`,
      category: "booking",
      dueDate: "2 weeks before departure",
      notes: "Cross-reference check-in times and secure your reservation voucher details.",
      completed: false
    },
    {
      id: "chk-3",
      task: `Pack climate-suitable apparel suited for local seasonal forecasts`,
      category: "packing",
      dueDate: "2 days before departure",
      notes: `Typically angenehm 70-80F degrees but worth checking weather forecasts.`,
      completed: false
    },
    {
      id: "chk-4",
      task: `Pre-purchase passes or skip-the-line admissions online`,
      category: "booking",
      dueDate: "1 week before departure",
      notes: "Predefined activities like premium boat routes require advanced reservations.",
      completed: false
    }
  ];

  return {
    destination: destClean,
    durationDays: Number(durationDays),
    citizenshipStatus: citizenship,
    visaConditions: isInternational 
      ? `Holders of a ${citizenship} passport entering ${destination} typically receive Visa-Free entry length or e-Visa privileges (up to 30 to 90 days depending on immigration portals). Ensure your passport remains fully valid for at least six months from your selected dates.`
      : `Excellent news! Since this is a Domestic Trip, standard US domestic regulations apply. No international physical visa is necessary; simply travel with valid state-issued identity documents.`,
    recommendedTravelDates: datesLabel,
    whyThisRecommendation: `We optimized these recommendations specifically according to your custom $${totalDaily}/day daily multiplier, tailored for ${peopleCount} participant(s). We selected ${accommodationType === 'both' ? "a mix of hotels & boutique Airbnbs" : accommodationType === "ai_recommended" ? "the most strategic lodging type dynamically recommended by AI" : accommodationType} and structured timing sequences around a highly engaging ${pace} pace to completely avoid fatigue while reflecting custom interests in ${selectedInterests.join(', ') || 'sightseeing'}.`,
    whyThisRecommendationLinks: [
      { title: `${destClean} Seasonal Climate & Packing Guide`, url: `https://www.google.com/search?q=${encodeURIComponent(destClean)}+seasonal+climate+and+packing+guide` },
      { title: `Local Transit & Logistics Advice for ${destClean}`, url: `https://www.google.com/search?q=${encodeURIComponent(destClean)}+local+transit+and+logistics+advice` }
    ],
    days,
    preTravelChecks,
    budget: {
      accommodation: {
        type: accommodationTitle,
        estimatedCost: accommodationCost,
        explanation: `Allocated roughly 45% of budget limits suited for private comfort stays.`,
        deepLink: hotelDeepLink
      },
      transport: {
        type: transportTitle,
        estimatedCost: transportCost,
        explanation: `Calculated for localized ${isRoadtrip ? "roadtrip scenic driving segments" : "comfortable city transfers"}.`,
        deepLink: transitDeepLink
      },
      activities: {
        estimatedCost: activitiesTotalLimit,
        explanation: `Includes dedicated budgets for specialized tour entry fees and guided sessions.`
      },
      foodAndMisc: {
        estimatedCost: foodCost,
        explanation: `Provides ample daily funds for delicious dining, coffee, and unexpected shopping.`
      },
      totalEstimated: totalTripCost,
      currency: "USD"
    },
    flightDetails: getFallbackFlights(departure, destination, preferredStops),
    accommodationRecommendation: {
      stayType: accommodationType === 'both' ? "split" : accommodationType === 'ai_recommended' ? "split" : accommodationType,
      heading: `Local Concierge Recommendation: Stay in style near central ${destClean}`,
      locationStrategy: isRoadtrip 
        ? `Split Stay Recommended: Set up Base 1 near the western side for scenic exploration, and Base 2 near the eastern/coast side for highlights.` 
        : `Single Base Recommended: Stay centrally inside the downtown / core cultural hub to enable rapid walking exploration and simple transit.`,
      detailedReasoning: `For ${destClean}, choosing ${accommodationType === 'both' ? 'a hybrid of cozy Airbnbs and premium hotels' : accommodationType === 'ai_recommended' ? 'the AI-selected custom lodging type (hotels or boutique private homes)' : accommodationType + 's'} provides a versatile blend of comfort, kitchens, and service support. Setting up base camp as suggested reduces overall backtracking, minimizes check-in friction, and coordinates beautifully with standard check-in hours at 15:00.`
    },
    isFallback: true
  };
}

// 2. Generate Comprehensive AI Itinerary Route
app.post("/api/itinerary/generate", async (req, res) => {
  let fallbackReason = "";
  try {
    const preferences = req.body;
    if (!preferences) {
      return res.status(400).json({ error: "Missing preferences in request body" });
    }

    const {
      citizenship,
      departure,
      destination,
      isInternational,
      isRoadtrip,
      roadtripType,
      hasDates,
      startDate,
      endDate,
      durationDays,
      departureTime,
      arrivalTime,
      accommodationType,
      transportType,
      pace,
      peopleCount,
      selectedInterests,
      customTags,
      avoidTags,
      budgetType,
      customDailyBudgetLimit,
      existingItinerary,
      preferredStops
    } = preferences;

    // Build the descriptive prompt
    let prompt = "";
    if (existingItinerary) {
      prompt += `You are editing and modifying an EXISTING itinerary that the user is currently looking at. 
DO NOT start from scratch. Instead, adjust the existing itinerary to match the new preferences (like changing dates, budget, pace, arrival/departure times, or travelers) while carefully preserving as much of the user's current specific activities, descriptions, manual edits, and customized structures as possible.

Here is the CURRENT Itinerary:
${JSON.stringify(existingItinerary, null, 2)}

Please apply the following updated travel choices to update and refine it:
`;
    } else {
      prompt += "Create a highly comprehensive, custom travel itinerary for a trip. ";
    }

    prompt += `Here are the user's specific details:
- **Citizenship**: ${citizenship}
- **Departure Location**: ${departure}
- **Destination**: ${destination}
- **Flight Category**: ${isInternational ? "International Tour Session" : "Domestic Travel"}
- **Roadtrip Option**: ${isRoadtrip ? `Yes (${roadtripType === 'to_destination' ? "Roadtrip driving to the destination" : "Roadtrip driving purely around the destination"})` : "No"}
- **Dates**: ${hasDates ? `Preferred dates from ${startDate} to ${endDate}` : `To be recommended around late Spring/Summer 2026`}
- **Duration**: ${durationDays ? `${durationDays} Days` : "Recommend logical days for this specific destination"}
- **Preferred Arrival Time at Destination**: ${arrivalTime || "04:00 PM"} (on Day 1)
- **Preferred Departure Time from Destination**: ${departureTime || "10:00 AM"} (on last day)
- **Accommodation Preference**: ${accommodationType === 'ai_recommended' ? 'AI Recommended (You decide if hotels, airbnbs, or a hybrid/split thereof is the absolute best accommodation match for this specific destination, and customize the lodgings/stay details accordingly)' : accommodationType} (options include hotel, airbnb, or both)
- **Pace preference**: ${pace} (options: relaxed, balanced, adventurous)
- **Number of travelers**: ${peopleCount} participant(s)
- **Interested activities**: ${[...selectedInterests, ...customTags].join(", ")}
- **Things to AVOID if any**: ${avoidTags.join(", ")}
- **Client Budget Class**: ${budgetType} (aim at approximate typical daily costs of a ${budgetType} tier, with custom threshold: ${customDailyBudgetLimit ? "$" + customDailyBudgetLimit + "/day" : "standard dynamic local levels for this location"})
- **Preferred Flight Stops**: ${preferredStops || 'any'} (filters: nonstop, one, any)

CRITICAL REQUISITES & LOGIC TO ACCOUNT FOR:
1. **Visa and Entry Checks**: Explain visa requirements or exemptions for a holder of ${citizenship} citizenship entering ${destination} (considering if it is international). State exact visa status (visa free length, e-Visa, or physical stamp requirements).
2. **Transportation**: Explain the best transportation strategy based on options. Account for travel times (including airport/station transfers, or travel between different towns). Include specific driving segments with times if a roadtrip is requested.
3. **Accommodation Checks & Travel Times**: 
   - Incorporate Hotel check-in time (e.g. at 3 PM / 15:00 on arrival day) and check-out time (e.g. at 11 AM / 11:00 on departure day) explicitly as timed activities in the day plans.
   - Design Day 1 around the preferred arrival time of ${arrivalTime || "04:00 PM"}. If they arrive late, schedule only evening/dinner items. If they arrive early, schedule afternoon exploration.
   - Design the final day around the preferred departure time of ${departureTime || "10:00 AM"} so that checkout, transfer, and departure logistics are correctly sequenced and they do not have unrealistic activities scheduled after their departure time.
4. **Pre-booking alerts**: Provide a detailed list of pre-travel preparations (Pre-travel checklist) like ticket bookings in advance (e.g. for famous state parks, national parks, popular cruises, or premium restaurants).
5. **Real-world Deep Links**: Generate real-world search and booking deep-links:
   - Include deep search links to Hotel listings, Airbnb listings, Flight/travel bookings, or car rentals. Customize URLs with ${encodeURIComponent(destination)} to make them clickable deep links.
   - **MUST USE SPECIFIED TRAVEL DATES IN LINKS**: If travel dates are specified (${hasDates ? `from ${startDate} to ${endDate}` : 'not specified'}), you MUST append these dates to the search query strings in the booking URLs so users get live real-market values.
   - Example templates:
     - Booking.com: 'https://www.booking.com/searchresults.html?ss=POS_TAG_NAME${hasDates && startDate && endDate ? `&checkin=${startDate}&checkout=${endDate}` : ''}'
     - Airbnb: 'https://www.airbnb.com/s/POS_TAG_NAME/homes${hasDates && startDate && endDate ? `?checkin=${startDate}&checkout=${endDate}` : ''}'
     - Google Flights/Search: 'https://www.google.com/search?q=google+flights+from+DEPART_CITY+to+DEST_CITY+departing+${startDate || ''}+returning+${endDate || ''}'
     - TripAdvisor/Rental: 'https://www.google.com/search?q=car+rental+in+DEST_CITY+from+${startDate || ''}+to+${endDate || ''}' or similar relevant travel window search strings. Replace placeholder spaces with '+'.
   - **CRITICAL QUALITY CONTROL**: For individual scheduled day activity booking links ("bookingDeepLink"), do NOT use generic Airbnb or Hotel links. Instead, create a specific Google Search query to find tickets, tables, or bookings for that specific attraction/activity (e.g., 'https://www.google.com/search?q=book+tickets+for+ATTRACTION_NAME+in+DEST_CITY' or 'https://www.google.com/search?q=reserve+table+at+RESTAURANT_NAME+in+DEST_CITY'). Real-world event and guided sightseeing bookings must point to such a search rather than an accommodation site.
6. **Timeline continuity**: Every activity must have a specific start and end time (times must format clearly, e.g., "09:00 AM - 10:30 AM"). Specify travel transitions in \`travelDetailsToNext\` and durations in \`travelTimeToNextMs\` (in minutes) where logical.
7. **EXTREME DETAIL & ACCURATE PACING DENSITY**:
   - For 'balanced' pace, you MUST schedule at least 4 to 5 distinct, highly-granular activities per day (e.g., Morning exploration, Mid-Morning Coffee Spot, Midday Lunch, Afternoon Attraction, and Dinner/Evening Event). Meticulously fill the day; do not leave days with only 1 or 2 items.
   - For 'adventurous' pace, you MUST schedule at least 5 to 6 distinct, action-packed activities per day (e.g. Morning Walk, breakfast placeholder spot, Afternoon guided tour, late Afternoon scenic viewpoint, Sunset lounge, and a themed dinner/night event).
   - For 'relaxed' pace, you can schedule 2 to 3 distinct activities.
   - NEVER use generic, vague, or high-level placeholders (e.g., do NOT just write "Explore the neighborhood", "Eat local food", "Visit a cathedral", or "Have dinner at a local spot").
   - EVERY activity name MUST reference a specific, real-world venue, restaurant, viewpoint, or sightseeing attraction (e.g., "Savor Traditional Tonkotsu Ramen at Ichiran Shinjuku" or "Scenic Ride on the historic Peak Tram to Victoria Peak").
   - Each and every single activity's 'description' must contain a deeply detailed paragraph of 3-4 sentences packed with real, highly practical concierge-level field knowledge. Name specific dishes to order (with local specialty name), exact viewpoint locations, little-known historical secrets, or real local hacks to avoid crowds.
8. **Seasonality, Closing Times & Day of Week Logic**:
   - Standard operating/opening hours and closing days of the week MUST be meticulously verified for all recommended sights, markets, and venues. You MUST determine the weekday for each sequential calendar date (e.g., Monday, Tuesday, Sunday) and ensure that no scheduled museum, local market, palace, castle, ferry, or attraction has closing day conflicts. For example, do not schedule the Louvre museum on Tuesdays; Versailles on Mondays; or standard wholesale fish markets/Tsukiji outer market on Sundays or Wednesdays.
   - Analyze the specific season, temperature, climate patterns, or month of travel (e.g., snow conditions or winter road closures in Banff/Jasper; cherry blossom times in Japan; extreme heat or seasonal monsoons; winter closures for cable cars/ferries). If a requested sight or adventure is closed, inaccessible, or seasonal-only during the user's travel window (${hasDates ? `from ${startDate} to ${endDate}` : `the chosen dates`}), you MUST replace it with a suitable, highly rewarding open alternative.
   - Carefully optimize the daily activity sequence to align with local daylight windows, seasonal climate factors, or specific daytime window constraints of the selected dates (${hasDates ? `from ${startDate} to ${endDate}` : `Spring/Summer 2026`}). If a conflict is detected, dynamically re-arrange, switch the activity order, or replace the venue with a highly engaging and open alternative. \n9. **Supporting Recommendation Links**:
    - Under 'whyThisRecommendationLinks', synthesize 2-3 specific Search queries/links justifying why these travel dates, transit choices, or locations were selected. Format the query strictly for Google search, TripAdvisor, or Wikipedia (replace spaces with '+'), with clear human-readable titles (e.g., 'Kyoto Cherry Blossom Forecast Guide', 'Paris Metro Transit Survival Guide', 'Tokyo Weather in June Guide').
10. **Flight Recommendations & Price Deal-Finding**:
    - Under 'flightDetails', you MUST keep the 'recommendedFlights' array completely EMPTY [] to allow users to search live real-time flights without pre-computed or hallucinated records.
    - Set the bookingDeepLink to a clickable Google Flights search: 'https://www.google.com/search?q=google+flights+from+DEPARTURE+to+DESTINATION${hasDates && startDate && endDate ? `+departing+${startDate}+returning+${endDate}` : ''}' (replacing DEPARTURE with the departure city/airport, and DESTINATION with the destination city).
    - Under 'dealAlert', output highly useful travel advice on potential savings (e.g., 'Tip: Tuesdays and Wednesdays are often cheaper days to depart. Avoid weekend departures.').
    - Under 'bestPriceAdvice', provide a brief 2-3 sentence overview of historical booking windows and seasonal pricing to secure the best fares on this route.
11. **Meticulous Calendar Date Spelling**:
    - Under the 'date' property of each item in the 'days' array, you MUST output the precise calendar date for that day of travel.
    - Calculate and formatted the calendar date sequentially. Spelled out completely with the weekday, month name, day, and year (e.g., "Wednesday, May 27, 2026" for Day 1, "Thursday, May 28, 2026" for Day 2, and so on).
    - If preferred travel dates are specified (${hasDates ? `from ${startDate} to ${endDate}` : 'not specified'}), calculate the calendar date for each day sequentially starting from ${startDate || 'June 15, 2026'}.
    - If dates were not specified, assume check-in / start date is Monday, June 15, 2026, and increment the days sequentially from there.
12. **AI Accommodation & Base Camp Recommendation**:
    - Under 'accommodationRecommendation', provide a highly creative, expert concierge stay blueprint tailored specifically to the geography of ${destination}.
    - It MUST analyze whether the user should split their nights in separate local base camps or stay in one place. For islands (like Hawaii, Maui), large cities (like Tokyo/Kyoto, Paris/Amalfi split), recommend setting up home base on certain sides of the city/island to avoid massive backtracking (e.g. 'Nights 1-2 on the East Side/Hilo for Volcanoes, Nights 3-5 on the West Side/Kona for sunny beaches', or 'stay at a boutique design hotel vs. fully equipped home rentals').
    - State 'stayType' (either 'hotel', 'airbnb', 'split', or 'other').
    - State 'heading' (e.g., 'Recommended: Airbnb & Boutique Hotel Split Stay').
    - State 'locationStrategy' (a concise, clear, scannable instruction on where to set up home base for which days/nights).
    - State 'detailedReasoning' (a full 3-4 sentence detailed paragraph justification explaining local layout benefits, travel time calculations, and standard hotel check-in/out guidelines).

Please output the result strictly in JSON according to this response schema. No commentary leading or trailing—MUST BE VALID PARSABLE JSON conforming to the structure described.`;

    console.log("Generating travel itinerary with Gemini API...");

    // Set a race promise to guarantee response in max 75 seconds, otherwise fallback gracefully
    // to keep the client extremely responsive and completely prevent stalling
    const apiCallPromise = generateContentWithRetryAndFallback({
      contents: prompt,
      systemInstruction: "You are an ultimate travel concierge who specializes in hyper-detailed, highly-specific real-world travel packages. Your itineraries are packed with real, specific venue names, specific streets, hidden local viewpoint locations, exact specialty dish recommendations to order, and meticulous timing. You provide modeled realistic flight recommendations with deep links to search live fares. NEVER use generic advice, high-level placeholders, or vague descriptions. Format precisely to standard JSON templates.",
      config: {
        responseMimeType: "application/json",
        responseSchema: itineraryResponseSchema,
        temperature: 0.1 // low temperature for highly structured compliance
      }
    });

    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error("Gemini API call exceeded standard threshold of 90 seconds")), 90000);
    });

    const { response, modelUsed }: any = await Promise.race([apiCallPromise, timeoutPromise]);
    const textOutput = response.text;
    if (!textOutput) {
      throw new Error("Empty text returned from Gemini API");
    }

    // Parse the returned JSON directly and return to user
    const itineraryData = JSON.parse(textOutput.trim());
    itineraryData.isFallback = false;
    itineraryData.modelUsed = modelUsed;
    return res.json(itineraryData);

  } catch (error: any) {
    console.warn("Failed to generate itinerary with Gemini API:", error.message || error);
    return res.status(500).json({
      error: "Unable to retrieve accurate, real-time travel information because the AI travel service experienced an error or timeout. Please refresh the page or try your selection again to re-initiate calibration.",
      details: error.message || String(error)
    });
  }
});

// 3. Optional AI Itinerary Modification Chat
app.post("/api/itinerary/modify", async (req, res) => {
  try {
    const { itinerary, message } = req.body;
    if (!itinerary || !message) {
      return res.status(400).json({ error: "Missing current itinerary or update message instruction." });
    }

    const prompt = `You are an elite, highly creative travel co-pilot and itinerary coordinator.
Your task is to review the current travel itinerary, listen to the user's request, and output BOTH a warm conversational response explaining the changes, and the COMPLETE updated travel itinerary JSON object.

Here is the current travel itinerary state:
${JSON.stringify(itinerary, null, 2)}

User's requested modification or question:
"${message}"

INSTRUCTIONS:
1. Revise the itinerary where requested:
   - If they request to change, swap, or remove activities, modify the "activities" arrays under the correct "days".
   - If they request to add/remove days, generate or remove days from the "days" array and update "durationDays" accordingly.
   - If they request to adjust the budget pace or target cost (e.g. "make it luxury" or "keep it low budget"), scale the estimated costs in "activities", "accommodation" and "transport" elements, and re-total in "budget.totalEstimated".
   - If they ask general travel guidance, keep the itinerary as is but answer comprehensively in 'assistantMessage'.
   - If they request specifically about airlines, stops, or flights, keep the "recommendedFlights" list empty, but provide highly targeted, customized deal alerts, price advice, and pre-filled deep links to Google Flights/Skyscanner/Kayak so they can instantly check actual seats on live systems.
2. Return JSON exactly of this structure:
{
  "assistantMessage": "Tell the user in 2-3 warm sentences exactly what changes you applied to their travel package and why they will love it.",
  "updatedItinerary": { ... COMPLETE REVISED ITINERARY following the exact metadata schema as the input itinerary ... }
}

3. Ensure that any newly added or modified activities follow the EXTREME DETAIL & REAL-WORLD VENUE RECOMMENDATIONS rule: name real, specific venues (not placeholders or generic terms), and write descriptive 3-4 sentence explanations with local tips (such as signature dishes to try or crowd-avoidance secrets).

CRITICAL: Keep the updatedItinerary schema extremely robust. It must contain 'days', 'preTravelChecks', 'budget', 'flightDetails', and all necessary sub-attributes. Do not omit existing days or activities unless explicitly asked to modify them. All activities must preserve their editable 'id' and correct structure.`;

    const { response, modelUsed } = await generateContentWithRetryAndFallback({
      contents: prompt,
      systemInstruction: "You are an ultimate travel concierge who specializes in hyper-detailed, highly-specific real-world travel packages. You receive a structured JSON travel itinerary and a human instruction, then make targeted, highly descriptive modifications naming real-world locations and dishes, and respond with both a friendly description and the completed updated JSON itinerary.",
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            assistantMessage: { type: Type.STRING, description: "Friendly travel assistant chat reply" },
            updatedItinerary: itineraryResponseSchema
          },
          required: ["assistantMessage", "updatedItinerary"]
        },
        temperature: 0.2
      }
    });

    const textOutput = response.text;
    if (!textOutput) {
      throw new Error("No output returned from Gemini modification session.");
    }

    const result = JSON.parse(textOutput.trim());
    if (result.updatedItinerary) {
      result.updatedItinerary.modelUsed = modelUsed;
    }
    return res.json(result);

  } catch (error: any) {
    console.warn("Failed to modify itinerary with Gemini AI:", error.message || error);
    return res.status(500).json({ 
      error: "Unable to complete modification request with our AI companion because the service experienced an error or timeout. Please refresh the page and try your request again.",
      details: error.message || String(error)
    });
  }
});

// Serve frontend assets
if (process.env.NODE_ENV !== "production") {
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: "spa",
  });
  app.use(vite.middlewares);
} else {
  const distPath = path.join(process.cwd(), "dist");
  app.use(express.static(distPath));
  app.get("*", (req, res) => {
    res.sendFile(path.join(distPath, "index.html"));
  });
}

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
